version: 2
updates:
  # Node.js dependencies (package.json / package-lock.json / yarn.lock)
  - package-ecosystem: "npm"
    directory: "../"  
    schedule:
      interval: "daily"  
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "express"
        versions: ["^5.0.0"]

  # Rust dependencies (Cargo.toml)
  - package-ecosystem: "cargo"
    directory: "../"           # Location of Cargo.toml
    schedule:
      interval: "weekly" 
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 5
