name: CI

# Trigger on push or pull request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Setup Python on Windows
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if exist requirements.txt pip install -r requirements.txt

      # Run tests
      - name: Run tests
        run: |
          if exist tests pytest
