name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Install components
        run: rustup component add clippy rustfmt

      - name: Format check
        run: cargo fmt -- --check

      - name: Lint check
        run: cargo clippy -- -D warnings

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
